### ISSUE TITLE
[TAs] please update the author/paper/venue formatting

### ISSUE THREAD

**Issue by AI599** [AI599/spring-2022#2]
please update papers in the reading list/schedule to follow the following author/paper/venue formatting. Some are already in the correct format, some aren't (finished up to week 4)

Examples: 

Han, Dongyoon, et al. "Rethinking channel dimensions for efficient model design.", CVPR 2021
Tolstikhin, Ilya O., et al. "Mlp-mixer: An all-mlp architecture for vision.", NeuIPS 2021
Dosovitskiy, Alexey, et al. "An image is worth 16x16 words: Transformers for image recognition at scale." ICLR 2021
Heo, Byeongho, et al. "Rethinking spatial dimensions of vision transformers.", ICCV 2021
Khan, Salman, et al. "Transformers in vision: A survey.", arXiv 2021

**it's the MLA convention (you can get it from google scholar's "cite" action), but with the abbreviated venue name.**

**Comment by AI599** [comment]
let's try to address this by Thursday 3/3 23:55

**Comment by AI599** [comment]
please use branches

**Comment by minsukchang** [comment]
Thanks!!
